[package]
name = "type-theory-backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mybin"
path = "src/bin.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.2"
